"""PDF generation service using ReportLab."""
from io import BytesIO
from datetime import date


def generate_plan_pdf(plan) -> bytes:
    """Generate a PDF for a study plan. Returns bytes."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        )
        from reportlab.lib import colors
    except ImportError:
        # Fallback if reportlab not installed
        return _generate_simple_pdf(plan)

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1 * inch, bottomMargin=0.5 * inch)
    styles = getSampleStyleSheet()
    story = []

    # ── Title ────────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        "PlanTitle",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=HexColor("#6C3CE0"),
        spaceAfter=6,
    )
    story.append(Paragraph(plan.title or "Study Plan", title_style))
    story.append(Spacer(1, 12))

    # ── Meta info ────────────────────────────────────────────────────────
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"], fontSize=11, textColor=HexColor("#666666")
    )
    start = plan.start_date.strftime("%B %d, %Y") if plan.start_date else "N/A"
    end = plan.end_date.strftime("%B %d, %Y") if plan.end_date else "N/A"
    story.append(Paragraph(f"<b>Period:</b> {start} — {end}", meta_style))
    story.append(Paragraph(f"<b>Status:</b> {plan.status or 'active'}", meta_style))
    if plan.coordinator_notes:
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<i>{plan.coordinator_notes}</i>", meta_style))
    story.append(Spacer(1, 20))

    # ── Sessions table ───────────────────────────────────────────────────
    sessions = sorted(plan.sessions, key=lambda s: (str(s.session_date), s.start_time))
    if sessions:
        table_data = [["Date", "Time", "Subject", "Topic", "Duration", "Status"]]
        for s in sessions:
            sdate = s.session_date.strftime("%a %b %d") if s.session_date else ""
            stime = s.start_time.strftime("%H:%M") if hasattr(s.start_time, "strftime") else str(s.start_time)
            etime = s.end_time.strftime("%H:%M") if hasattr(s.end_time, "strftime") else str(s.end_time)
            time_slot = f"{stime} – {etime}"
            status_text = "✓ Done" if s.completed else "Pending"
            table_data.append([
                sdate, time_slot, s.subject_name or "",
                (s.topic or "")[:40], f"{s.duration_minutes}m", status_text,
            ])

        table = Table(table_data, colWidths=[1.1 * inch, 1.0 * inch, 1.2 * inch, 1.6 * inch, 0.7 * inch, 0.7 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#6C3CE0")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E0E0E0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#F8F6FF"), colors.white]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(table)
    else:
        story.append(Paragraph("No sessions in this plan.", styles["Normal"]))

    # ── Footer ───────────────────────────────────────────────────────────
    story.append(Spacer(1, 30))
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#999999")
    )
    story.append(Paragraph(
        f"Generated by StudyMind AI on {date.today().strftime('%B %d, %Y')}",
        footer_style,
    ))

    doc.build(story)
    return buffer.getvalue()


def _generate_simple_pdf(plan) -> bytes:
    """Ultra-simple fallback if reportlab is missing."""
    content = f"Study Plan: {plan.title}\n"
    content += f"Period: {plan.start_date} to {plan.end_date}\n\n"
    for s in plan.sessions:
        content += f"- {s.session_date} {s.start_time}-{s.end_time}: {s.subject_name} — {s.topic}\n"
    return content.encode("utf-8")
