import React, { useState, useEffect } from 'react';
import { api } from '../lib/api';
import { 
  FileQuestion, 
  Sparkles, 
  CheckCircle, 
  XCircle, 
  AlertCircle,
  HelpCircle,
  Clock,
  BookOpen
} from 'lucide-react';
import toast from 'react-hot-toast';

export const QuizPage: React.FC = () => {
  const [quizzes, setQuizzes] = useState<any[]>([]);
  const [subjects, setSubjects] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Generate settings
  const [selectedSubject, setSelectedSubject] = useState('');
  const [difficulty, setDifficulty] = useState(3);
  const [numQuestions, setNumQuestions] = useState(5);
  const [topic, setTopic] = useState('');

  // Active quiz screen state
  const [activeQuiz, setActiveQuiz] = useState<any>(null);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [currentQuestionIdx, setCurrentQuestionIdx] = useState(0);

  // Results screen state
  const [quizResult, setQuizResult] = useState<any>(null);

  const loadInitialData = async () => {
    try {
      setLoading(true);
      const [qRes, sRes] = await Promise.all([
        api.quizzes.list(),
        api.subjects.list(),
      ]);
      setQuizzes(qRes);
      setSubjects(sRes);
      if (sRes.length > 0) {
        setSelectedSubject(sRes[0].id);
      }
    } catch (err: any) {
      toast.error('Failed to load quiz list: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadInitialData();
  }, []);

  const handleGenerateQuiz = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedSubject) {
      toast.error('Please select a subject');
      return;
    }
    setSubmitting(true);
    try {
      const q = await api.quizzes.generate({
        subject_id: selectedSubject,
        topic: topic || undefined,
        difficulty,
        num_questions: numQuestions,
      });
      setActiveQuiz(q);
      setAnswers({});
      setCurrentQuestionIdx(0);
      setQuizResult(null);
      toast.success('AI Agent generated a new quiz for you!');
    } catch (err: any) {
      toast.error('Could not generate quiz: ' + err.message);
    } finally {
      setSubmitting(false);
    }
  };

  const handleSelectOption = (questionId: string, opt: string) => {
    setAnswers({ ...answers, [questionId]: opt });
  };

  const handleShortAnswerChange = (questionId: string, val: string) => {
    setAnswers({ ...answers, [questionId]: val });
  };

  const handleSubmitQuiz = async () => {
    if (!activeQuiz) return;
    setSubmitting(true);
    try {
      const formattedAnswers = Object.entries(answers).map(([qId, val]) => ({
        question_id: qId,
        answer: val,
      }));
      const result = await api.quizzes.submit(activeQuiz.id, formattedAnswers);
      setQuizResult(result);
      // Refresh list
      const qList = await api.quizzes.list();
      setQuizzes(qList);
      toast.success('Quiz submitted! Analytics Agent computed results.');
    } catch (err: any) {
      toast.error('Failed to submit quiz: ' + err.message);
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex h-[60vh] items-center justify-center">
        <div className="h-10 w-10 animate-spin rounded-full border-4 border-purple-500 border-t-transparent" />
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="border-b border-glass-border pb-4">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <FileQuestion className="h-6 w-6 text-purple-400" />
          <span>Interactive Quiz Room</span>
        </h2>
        <p className="text-xs text-gray-400 mt-1">
          Take assessments generated by the Quiz agent and receive feedback from the Analytics agent.
        </p>
      </div>

      {!activeQuiz && !quizResult ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Settings panel */}
          <div className="glass-card p-6 h-fit lg:col-span-1">
            <h3 className="text-md font-bold text-white mb-4 flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-400" />
              <span>Generate Quiz</span>
            </h3>
            {subjects.length === 0 ? (
              <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-400 text-xs flex gap-2">
                <AlertCircle className="h-5 w-5 shrink-0" />
                <span>Create subjects before generating quizzes.</span>
              </div>
            ) : (
              <form onSubmit={handleGenerateQuiz} className="space-y-4">
                <div>
                  <label className="block text-xs font-semibold text-gray-400 mb-1">Subject</label>
                  <select
                    value={selectedSubject}
                    onChange={(e) => setSelectedSubject(e.target.value)}
                    className="input-field bg-dark-800"
                  >
                    {subjects.map((sub) => (
                      <option key={sub.id} value={sub.id}>
                        {sub.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-gray-400 mb-1">Topic / Keywords (Optional)</label>
                  <input
                    type="text"
                    placeholder="e.g. Chapter 3, Linear Systems"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    className="input-field"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-gray-400 mb-1">Difficulty Level (1-5)</label>
                  <div className="flex gap-2">
                    {[1, 2, 3, 4, 5].map((lvl) => (
                      <button
                        key={lvl}
                        type="button"
                        onClick={() => setDifficulty(lvl)}
                        className={`flex-1 py-1.5 rounded-lg text-xs font-mono font-bold transition-all border ${
                          difficulty === lvl
                            ? 'bg-purple-500/20 text-purple-300 border-purple-500'
                            : 'bg-dark-800 border-glass-border text-gray-400 hover:bg-glass-white'
                        }`}
                      >
                        {lvl}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-gray-400 mb-1">Number of Questions</label>
                  <select
                    value={numQuestions}
                    onChange={(e) => setNumQuestions(parseInt(e.target.value) || 5)}
                    className="input-field bg-dark-800"
                  >
                    <option value={3}>3 Questions</option>
                    <option value={5}>5 Questions</option>
                    <option value={8}>8 Questions</option>
                    <option value={10}>10 Questions</option>
                  </select>
                </div>

                <button
                  type="submit"
                  disabled={submitting}
                  className="w-full btn-primary py-2.5 flex items-center justify-center gap-2"
                >
                  {submitting ? (
                    <div className="h-5 w-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4" />
                      <span>Request Quiz</span>
                    </>
                  )}
                </button>
              </form>
            )}
          </div>

          {/* Previous Quizzes List */}
          <div className="lg:col-span-2 space-y-4">
            <h3 className="text-md font-bold text-white">Quiz Log</h3>
            {quizzes.length === 0 ? (
              <div className="glass-card p-12 text-center text-gray-500">
                <FileQuestion className="h-10 w-10 mx-auto text-gray-600 mb-2" />
                <p className="text-sm">No quizzes completed yet.</p>
              </div>
            ) : (
              <div className="space-y-3">
                {quizzes.map((q) => (
                  <div key={q.id} className="glass-card p-5 flex items-center justify-between gap-4">
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-bold text-purple-400 bg-purple-500/10 px-2 py-0.5 rounded-full">
                          {q.subject_name}
                        </span>
                        {q.topic && <span className="text-xs font-semibold text-gray-200">({q.topic})</span>}
                      </div>
                      <span className="text-[10px] text-gray-500 block">
                        Date: {new Date(q.created_at).toLocaleDateString()}
                      </span>
                    </div>

                    <div className="flex items-center gap-3">
                      {q.status === 'completed' ? (
                        <span className="text-xs font-mono font-bold text-teal-400 px-3 py-1 bg-teal-500/10 rounded-xl border border-teal-500/20">
                          Score: {Math.round(q.score * 100)}%
                        </span>
                      ) : (
                        <button
                          onClick={() => {
                            setActiveQuiz(q);
                            setAnswers({});
                            setCurrentQuestionIdx(0);
                          }}
                          className="btn-secondary py-1 text-xs"
                        >
                          Resume Quiz
                        </button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      ) : activeQuiz ? (
        // Active Quiz Questionnaire View
        <div className="max-w-2xl mx-auto space-y-6">
          {/* Progress bar */}
          <div className="flex justify-between items-center text-xs text-gray-400 shrink-0">
            <span>
              Question {currentQuestionIdx + 1} of {activeQuiz.questions.length}
            </span>
            <span>{Math.round(((currentQuestionIdx + 1) / activeQuiz.questions.length) * 100)}% Complete</span>
          </div>

          <div className="h-1.5 w-full bg-dark-800 rounded-full overflow-hidden border border-glass-border shrink-0">
            <div 
              className="h-full bg-purple-500 transition-all duration-300"
              style={{ width: `${((currentQuestionIdx + 1) / activeQuiz.questions.length) * 100}%` }}
            />
          </div>

          {/* Active Question card */}
          {activeQuiz.questions[currentQuestionIdx] && (
            <div className="glass-card p-6 md:p-8 space-y-6">
              <h3 className="text-base md:text-lg font-bold text-white leading-relaxed">
                {activeQuiz.questions[currentQuestionIdx].question_text}
              </h3>

              {activeQuiz.questions[currentQuestionIdx].question_type === 'multiple_choice' ? (
                <div className="space-y-2">
                  {activeQuiz.questions[currentQuestionIdx].options?.map((opt: string, oIdx: number) => {
                    const isSelected = answers[activeQuiz.questions[currentQuestionIdx].id] === opt;
                    return (
                      <button
                        key={oIdx}
                        type="button"
                        onClick={() => handleSelectOption(activeQuiz.questions[currentQuestionIdx].id, opt)}
                        className={`w-full text-left p-4 rounded-xl border text-xs transition-all ${
                          isSelected
                            ? 'bg-purple-500/10 border-purple-500 text-purple-200'
                            : 'bg-glass-white border-glass-border text-gray-300 hover:bg-glass-hover'
                        }`}
                      >
                        {opt}
                      </button>
                    );
                  })}
                </div>
              ) : (
                <div>
                  <label className="block text-[10px] font-semibold text-gray-500 uppercase tracking-wider mb-2">
                    Your Answer
                  </label>
                  <textarea
                    placeholder="Type your explanation/answer details..."
                    value={answers[activeQuiz.questions[currentQuestionIdx].id] || ''}
                    onChange={(e) => handleShortAnswerChange(activeQuiz.questions[currentQuestionIdx].id, e.target.value)}
                    className="input-field h-28 resize-none"
                  />
                </div>
              )}
            </div>
          )}

          {/* Nav buttons */}
          <div className="flex justify-between items-center shrink-0">
            <button
              disabled={currentQuestionIdx === 0}
              onClick={() => setCurrentQuestionIdx(currentQuestionIdx - 1)}
              className="btn-secondary py-2 text-xs"
            >
              Previous
            </button>

            {currentQuestionIdx < activeQuiz.questions.length - 1 ? (
              <button
                onClick={() => setCurrentQuestionIdx(currentQuestionIdx + 1)}
                className="btn-primary py-2 text-xs"
              >
                Next Question
              </button>
            ) : (
              <button
                onClick={handleSubmitQuiz}
                disabled={submitting}
                className="btn-primary py-2 text-xs bg-teal-500 hover:bg-teal-400 shadow-teal-glow/20"
              >
                {submitting ? 'Submitting...' : 'Submit Answers'}
              </button>
            )}
          </div>
        </div>
      ) : (
        // Results View
        <div className="max-w-2xl mx-auto space-y-6">
          <div className="glass-card p-6 md:p-8 space-y-6 text-center">
            <div className="inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-teal-500/10 text-teal-400 border border-teal-500/20 mb-2">
              <CheckCircle className="h-10 w-10 animate-float" />
            </div>
            
            <h3 className="text-xl font-bold text-white">Quiz Analytics Assessment</h3>
            
            <div className="flex justify-center items-baseline gap-1 mt-2">
              <span className="text-3xl font-extrabold text-teal-400">{quizResult.correct}</span>
              <span className="text-gray-500">/</span>
              <span className="text-lg text-gray-400 font-semibold">{quizResult.total} Correct</span>
              <span className="text-xs text-gray-500 font-mono ml-3">({Math.round(quizResult.percentage)}%)</span>
            </div>

            {/* Agent Feedback text block */}
            <div className="p-4 rounded-xl bg-purple-500/5 border border-purple-500/10 text-left text-xs text-gray-300 leading-relaxed max-w-lg mx-auto">
              <h4 className="font-bold text-purple-400 mb-2 flex items-center gap-1">
                <Sparkles className="h-4 w-4" />
                <span>AI Agent Review Notes</span>
              </h4>
              <div className="space-y-1">
                {quizResult.feedback.split('\n').map((line: string, i: number) => {
                  if (line.startsWith('**') || line.startsWith('Performance')) {
                    return <p key={i} className="font-bold text-white my-1">{line}</p>;
                  }
                  if (line.startsWith('-')) {
                    return <li key={i} className="ml-4 list-disc text-gray-300">{line.slice(1).trim()}</li>;
                  }
                  return <p key={i} className="my-1 text-gray-400">{line}</p>;
                })}
              </div>
            </div>

            <button
              onClick={() => {
                setActiveQuiz(null);
                setQuizResult(null);
              }}
              className="btn-primary py-2 text-xs"
            >
              Back to Quiz Lobby
            </button>
          </div>

          {/* Questions review details */}
          <div className="space-y-4">
            <h3 className="text-sm font-bold text-white">Review Questions</h3>
            {quizResult.questions.map((q: any, idx: number) => (
              <div key={q.id} className="glass-card p-5 space-y-3 relative overflow-hidden">
                <div className="flex justify-between items-start gap-2">
                  <h4 className="text-sm font-semibold text-gray-200 leading-relaxed pr-8">
                    {idx + 1}. {q.question_text}
                  </h4>
                  <span className="shrink-0">
                    {q.is_correct ? (
                      <CheckCircle className="h-5 w-5 text-teal-400" />
                    ) : (
                      <XCircle className="h-5 w-5 text-red-400" />
                    )}
                  </span>
                </div>

                <div className="text-xs space-y-1 border-t border-glass-border/40 pt-3">
                  <div>
                    <span className="text-gray-500">Your Answer:</span>{' '}
                    <span className={q.is_correct ? 'text-teal-400 font-semibold' : 'text-red-400 font-semibold'}>
                      {q.user_answer || 'No answer provided'}
                    </span>
                  </div>
                  {!q.is_correct && (
                    <div>
                      <span className="text-gray-500">Correct Answer:</span>{' '}
                      <span className="text-teal-400 font-semibold">{q.correct_answer}</span>
                    </div>
                  )}
                  {q.explanation && (
                    <div className="text-[10px] text-gray-400 mt-2 bg-dark-800/40 p-2 rounded border border-glass-border">
                      <span className="font-semibold text-purple-400 block mb-0.5">Explanation</span>
                      {q.explanation}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
